# build_direct.ps1 — 使用已知 MSVC 路径编译（参照 abe_decrypt\build2.ps1 的成功方式）
#
# 前提条件（与 abe_decrypt\build2.ps1 完全相同）:
#   - C:\cl_x64\cl.exe  (从 MSVC bin 目录复制)
#   - C:\msvc           (junction -> MSVC toolchain)
#   - C:\winsdk         (junction -> Windows SDK)
#
# 用法:
#   .\build_direct.ps1              # 编译 separated (injector.exe + payload_dll.dll)
#   .\build_direct.ps1 -Combined    # 追加编译 combined (all_in_one.exe)
#   .\build_direct.ps1 -SkipPayload # 跳过 payload，直接复制已有 DLL

param(
    [switch]$Combined,
    [switch]$SkipPayload,
    [string]$ExistingDll = "D:\ClaudeCode-Home\JoyAI\abe_decrypt\bin\payload_dll.dll"
)

$ErrorActionPreference = 'Stop'
$VER  = '10.0.26100.0'
$SDK  = 'C:\winsdk'
$MSVC = 'C:\msvc'
$ROOT = Split-Path -Parent $MyInvocation.MyCommand.Path
$SEP  = "$ROOT\separated"
$COMB = "$ROOT\combined"
$OUT_SEP  = "$SEP\bin"
$OUT_COMB = "$COMB\bin"
New-Item -ItemType Directory -Force -Path $OUT_SEP  | Out-Null
New-Item -ItemType Directory -Force -Path $OUT_COMB | Out-Null

$I1 = $MSVC + '\include'
$I2 = $SDK  + '\Include\' + $VER + '\um'
$I3 = $SDK  + '\Include\' + $VER + '\shared'
$I4 = $SDK  + '\Include\' + $VER + '\ucrt'
$LU = $SDK  + '\Lib\' + $VER + '\um\x64'
$LC = $SDK  + '\Lib\' + $VER + '\ucrt\x64'
$LM = $MSVC + '\lib\x64'

$SRC_LINK = 'C:\abebuild_src2'
if (Test-Path $SRC_LINK) { cmd /c "rmdir $SRC_LINK" | Out-Null }
cmd /c "mklink /J $SRC_LINK `"$ROOT`"" | Out-Null

$TMP = 'C:\abebuild_out'
New-Item -ItemType Directory -Force -Path $TMP | Out-Null

# ══════════════════════════════════════════════════════════════════════════════
# 1. payload_dll.dll
# ══════════════════════════════════════════════════════════════════════════════
$payloadDll = "$TMP\payload_dll.dll"

if ($SkipPayload -and (Test-Path $ExistingDll)) {
    Write-Host "[*] Using existing DLL: $ExistingDll"
    Copy-Item $ExistingDll $payloadDll -Force
} else {
    Write-Host "[*] Building payload_dll.dll ..."
    $p = Start-Process -FilePath 'C:\cl_x64\cl.exe' `
        -ArgumentList @(
            '/nologo', '/O2', '/EHsc', '/MD', '/LD', '/GS-',
            "/I$I1", "/I$I2", "/I$I3", "/I$I4",
            "$SRC_LINK\separated\payload_dll.cpp",
            "/Fo$TMP\",
            '/link', '/DLL',
            "$LM\msvcrt.lib", "$LC\ucrt.lib",
            "$LU\kernel32.lib", "$LU\ole32.lib", "$LU\oleaut32.lib", "$LU\user32.lib",
            "/OUT:$payloadDll"
        ) -Wait -PassThru -NoNewWindow
    if ($p.ExitCode -ne 0) { throw "payload_dll.dll FAILED" }
    Write-Host "[+] payload_dll.dll OK"
}
Copy-Item $payloadDll $OUT_SEP -Force

# ══════════════════════════════════════════════════════════════════════════════
# 2. injector.exe
# ══════════════════════════════════════════════════════════════════════════════
Write-Host "[*] Building injector.exe ..."
$p2 = Start-Process -FilePath 'C:\cl_x64\cl.exe' `
    -ArgumentList @(
        '/nologo', '/O2', '/EHsc', '/MD',
        "/I$I1", "/I$I2", "/I$I3", "/I$I4",
        "$SRC_LINK\separated\injector.cpp",
        "/Fo$TMP\",
        '/link',
        "$LM\msvcrt.lib", "$LC\ucrt.lib",
        "$LU\kernel32.lib", "$LU\ole32.lib", "$LU\oleaut32.lib", "$LU\user32.lib",
        "$LU\advapi32.lib", "$LU\shell32.lib", "$LU\crypt32.lib",
        "/OUT:$TMP\injector.exe"
    ) -Wait -PassThru -NoNewWindow
if ($p2.ExitCode -ne 0) { throw "injector.exe FAILED" }
Write-Host "[+] injector.exe OK"
Copy-Item "$TMP\injector.exe" $OUT_SEP -Force

# ══════════════════════════════════════════════════════════════════════════════
# 3. all_in_one.exe (optional)
# ══════════════════════════════════════════════════════════════════════════════
if ($Combined) {
    Write-Host "[*] Generating generated_dll_bytes.h ..."
    $dllBytes   = [System.IO.File]::ReadAllBytes($payloadDll)
    $headerPath = "$TMP\generated_dll_bytes.h"
    $sb = [System.Text.StringBuilder]::new()
    $null = $sb.AppendLine("// Auto-generated by build_direct.ps1 - DO NOT EDIT")
    $null = $sb.AppendLine("#pragma once")
    $null = $sb.AppendLine("#define PAYLOAD_DLL_BYTES_INCLUDED")
    $null = $sb.AppendLine("static const unsigned char g_PayloadDllBytes[] = {")
    $line2 = @()
    for ($i = 0; $i -lt $dllBytes.Length; $i++) {
        $line2 += ("0x{0:X2}" -f $dllBytes[$i])
        if ($line2.Count -eq 16 -or $i -eq ($dllBytes.Length - 1)) {
            $t = if ($i -eq ($dllBytes.Length - 1)) { "" } else { "," }
            $null = $sb.AppendLine("    $($line2 -join ', ')$t")
            $line2 = @()
        }
    }
    $null = $sb.AppendLine("};")
    $null = $sb.AppendLine("static const size_t g_PayloadDllSize = sizeof(g_PayloadDllBytes);")
    [System.IO.File]::WriteAllText($headerPath, $sb.ToString(), [System.Text.Encoding]::UTF8)
    Copy-Item $headerPath "$COMB\generated_dll_bytes.h" -Force
    Write-Host "[+] Header: $($dllBytes.Length) bytes"

    Write-Host "[*] Building all_in_one.exe ..."
    $p3 = Start-Process -FilePath 'C:\cl_x64\cl.exe' `
        -ArgumentList @(
            '/nologo', '/O2', '/EHsc', '/MD',
            "/I$I1", "/I$I2", "/I$I3", "/I$I4", "/I$TMP",
            "$SRC_LINK\combined\all_in_one.cpp",
            "/Fo$TMP\",
            '/link',
            "$LM\msvcrt.lib", "$LC\ucrt.lib",
            "$LU\kernel32.lib", "$LU\ole32.lib", "$LU\oleaut32.lib", "$LU\user32.lib",
            "$LU\advapi32.lib", "$LU\shell32.lib", "$LU\crypt32.lib",
            "/OUT:$TMP\all_in_one.exe"
        ) -Wait -PassThru -NoNewWindow
    if ($p3.ExitCode -ne 0) { throw "all_in_one.exe FAILED" }
    Write-Host "[+] all_in_one.exe OK"
    Copy-Item "$TMP\all_in_one.exe" $OUT_COMB -Force
}

# ── 清理 ──────────────────────────────────────────────────────────────────────
cmd /c "rmdir $SRC_LINK" | Out-Null

Write-Host ""
Write-Host "=== Build complete ==="
Write-Host "  $OUT_SEP\payload_dll.dll"
Write-Host "  $OUT_SEP\injector.exe"
if ($Combined) { Write-Host "  $OUT_COMB\all_in_one.exe" }
Write-Host ""
Write-Host "Usage (Admin PowerShell):"
Write-Host "  .\separated\bin\injector.exe"
if ($Combined) { Write-Host "  .\combined\bin\all_in_one.exe" }
